version: "3.8"

services:

  taskman-service:
    image: openjdk:22-jdk-oracle
    container_name: taskmanimage
    env_file:
      - .env
    ports:
      - 8081:8080
      - 8001:8000
    expose:
      - "8001"
    depends_on:
      - taskman-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/TaskManagerService-v1.5.3.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  taskman-db:
    image: mongo:latest
    container_name: taskmandb
    ports:
      - 27016:27017
    volumes:
      - mongo_taskman:/etc/mongo
      - mongo_taskman_data:/data/db
      - mongo_taskman_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:
    name: greenspot_net

volumes:
    mongo_taskman:
    mongo_taskman_data:
    mongo_taskman_config:
