name: Dev Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Forced build'
  push:
    branches:
      - dev
    paths:
      - '**/*.java'
      - '**/application.properties'
      - '**/resources/*'
      - '*.gradle'

jobs:
  build:
    name: Build Service Jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: service-jar
          path: build/libs/*.jar

  deploy:
    name: Deploy Service
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: service-jar

      - name: Deploy
        run: |
          echo "Deploying service jar to server"
          scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} *.jar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}TASK